---
title: "Untitled"
author: "Masumbuko Semba"
date: "7/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require(tidyverse)
```

```{r}

files = dir(path = "FISH STAT/", 
            all.files = TRUE, 
            include.dirs = TRUE, 
            recursive = TRUE, 
            full.names = TRUE)

```

```{r}
file.meta = files %>% as_tibble() %>% 
  separate(col = value, into = c("a", "site"), sep = "/") %>%
  separate(col = site, into = c("a", "site"), sep = "-") %>%
  separate(col = site, into = c("site", "date"), sep = " ") %>%
  separate(col = date, into = c("date", "a"), sep = -4) %>%
  mutate(date = lubridate::mdy(date)) %>%
  select(1:2)
```

## Unit Data

```{r}

unit.data = list()

for (i in 1:length(files)){

meta.date = readxl::read_excel(files[i], sheet = 2, skip = 3, n_max = 6, 
                               col_types = c("text", "date", "numeric", "guess")) 
meta.text = readxl::read_excel(files[i], sheet = 2, skip = 3, n_max = 6, 
                               col_types = c("text", "text", "numeric", "guess"))

data = readxl::read_excel(files[i], sheet = 2, skip = 11) %>% 
  janitor::clean_names() 

unit.data[[i]] =  data%>%
  slice(1:11) %>%
  select(variable = 1, unit_1 = 2, unit_2 = 5, unit_3 = 8) %>%
  bind_cols(
    data%>%
      slice(14:24) %>%
      select(unit_4 = 2, unit_5 = 5, unit_6 = 8) 
  ) %>% 
  bind_cols(
    data%>% 
      slice(27:37) %>% 
      select(unit_7 = 2, unit_8 = 5, unit_9 = 8) 
    ) %>%
  pivot_longer(cols = 2:10, names_to = "units", values_to = "data") %>%
  mutate(date = meta.date$KIGOMA[2], 
         site = meta.text$KIGOMA[1],
         table = "unit") %>%
  select(date, site, table, everything())
}

unit.data = unit.data %>% 
  bind_rows() %>%
  arrange(date) %>%
  mutate(data = na_if(data, 0))
```

## Small fish sample

```{r}

small.fish.sample = list()

for (i in 1:length(files)){

meta.date = readxl::read_excel(files[i], sheet = 2, skip = 3, n_max = 6, 
                               col_types = c("text", "date", "numeric", "guess")) 
meta.text = readxl::read_excel(files[i], sheet = 2, skip = 3, n_max = 6, 
                               col_types = c("text", "text", "numeric", "guess"))

small.fish = readxl::read_excel(files[i], sheet = 2, skip = 54) %>% 
  janitor::clean_names() 

if (nrow(small.fish)==8)
  next

small.fish.sample[[i]] = small.fish%>%
  slice(1:4) %>%
  select(4:9) %>%
  pivot_longer(cols = 3:6, names_to = "small_fish", values_to = "value")%>%
  mutate(date = meta.date$KIGOMA[2], 
         site = meta.text$KIGOMA[1],
         table = "sample") %>%
  select(date, site, table, everything())
}

```



## Small fish composition

```{r}

small.fish.data = list()

for (i in 1:length(files)){

meta.date = readxl::read_excel(files[i], sheet = 2, skip = 3, n_max = 6, 
                               col_types = c("text", "date", "numeric", "guess")) 
meta.text = readxl::read_excel(files[i], sheet = 2, skip = 3, n_max = 6, 
                               col_types = c("text", "text", "numeric", "guess"))

small.fish = readxl::read_excel(files[i], sheet = 2, skip = 63) %>% 
  janitor::clean_names() 

if (nrow(small.fish)==8)
  next

small.fish.data[[i]] = small.fish%>%
  slice(1:2) %>%
  select(4:8) %>%
  rename(lstp =1,lstp_juv = 2, stolo = 3, limno = 4, others = 5) %>%
  pivot_longer(cols = 1:5, names_to = "small_fish", values_to = "value")%>%
  mutate(date = meta.date$KIGOMA[2], 
         site = meta.text$KIGOMA[1],
         table = "composition") %>%
  select(date, site, table, everything())
}

```